[project]
name = "genscai"
version = "0.1.0"
description = "Gen AI Recipes for Science and Research"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "icecream>=2.1.3",
    "notebook>=7.3.1",
    "polars>=1.18.0",
    "sciris>=3.2.0",
    "tinydb>=4.8.2",
    "tqdm>=4.67.1",
]
license = {file = "LICENSE"}


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["genscai*"]
