[project]
name = "genscai"
version = "0.1.0"
description = "Generative AI Tools and Recipes for Science and Research"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}

# pip dependencies
# install with `pip install -e .`
dependencies = [
    "beautifulsoup4",
    "torch",
    "huggingface_hub",
    "transformers",
    "accelerate",
    "sentencepiece",
    "pynvml",
    "ollama",
    "aisuite",
    "pandas",
    "tinydb",
    "openai",
    "sqlalchemy"
]

# optional pip dependencies
# install with `pip install -e '.[dev]'`
[project.optional-dependencies]
dev = [
    "black",
    "black[jupyter]",
    "pytest"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["genscai*"]

[tool.black]
target-version = ["py39", "py310", "py311", "py312", "py313"]
